use_frameworks!

platform :ios, '9.0'

target 'HLJZhongkeControl_Example' do
  pod 'HLJZhongkeControl', :path => '../'

  target 'HLJZhongkeControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
